services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Query\Type:
        parent: ezpublish.fieldType
        public: true
        autowire: true
        autoconfigure: false
        tags:
            - { name: ezplatform.field_type, alias: '%ezcontentquery_identifier%' }
        arguments:
            $queryTypeRegistry: '@ezpublish.query_type.registry'
            $identifier: '%ezcontentquery_identifier%'

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Mapper\QueryFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: '%ezcontentquery_identifier%' }
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'

    EzSystems\EzPlatformQueryFieldType\eZ\FieldType\Form\QueryFieldFormType: ~

    EzSystems\EzPlatformQueryFieldType\eZ\Persistence\Legacy\Content\FieldValue\Converter\QueryConverter:
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: '%ezcontentquery_identifier%' }

    Identifier\FieldDefinition:
        class: EzSystems\EzPlatformQueryFieldType\eZ\ContentView\FieldDefinitionIdentifierMatcher
        calls:
            - [setRepository, ['@ezpublish.api.repository']]
        tags:
            - { name: ezplatform.view.matcher }

    EzSystems\EzPlatformQueryFieldType\eZ\ContentView\QueryResultsInjector:
        arguments:
            $views: { field: '%ezcontentquery_field_view%', item: '%ezcontentquery_item_view%' }
        tags:
            - { name: kernel.event_subscriber }
