services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldRestController: ~

    EzSystems\EzPlatformQueryFieldType\API\QueryFieldService: ~

    EzSystems\EzPlatformQueryFieldType\ContentView\FieldDefinitionIdentifierMatcher:
        calls:
            - [setRepository, ['@ezpublish.api.repository']]

    Identifier\FieldDefinition: '@EzSystems\EzPlatformQueryFieldType\ContentView\FieldDefinitionIdentifierMatcher'

    EzSystems\EzPlatformQueryFieldType\ContentView\QueryResultsInjector:
        arguments:
            $views: { field: '%ezcontentquery_field_view%', item: '%ezcontentquery_item_view%' }
        tags:
            - { name: kernel.event_subscriber }
