imports:
    - { resource: fieldtypes.yml }
    - { resource: indexable_fieldtypes.yml }
    - { resource: field_value_converters.yml }
    - { resource: graphql.yml }

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldController: ~

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldRestController: ~

    EzSystems\EzPlatformQueryFieldType\API\QueryFieldService: ~
