system:
    default:
        fielddefinition_settings_templates:
            - { template: "EzSystemsEzPlatformQueryFieldTypeBundle::fielddefinition_settings.html.twig" }
        fielddefinition_edit_templates:
            - { template: "EzSystemsEzPlatformQueryFieldTypeBundle::field_types.html.twig" }
        field_templates:
            - { template: "EzSystemsEzPlatformQueryFieldTypeBundle::fieldtype_ui.html.twig" }
