services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldController: ~

    EzSystems\EzPlatformQueryFieldType\Controller\QueryFieldRestController: ~

    EzSystems\EzPlatformQueryFieldType\API\QueryFieldService: ~
